<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<script src="STHSMain.js"></script>
<title>ASHL - Pro Standing</title>
<script src="ASHL11-PRE.js"></script>
<meta name="author" content="Simon Tremblay, sths.simont.info" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="Decription" content="Simon Brassard - STHS - Version : 3.2.6.6 - ASHL11-STHS.db - ASHL11-STHSCareerStat.db"/>
<link href="STHSMain.css" rel="stylesheet" type="text/css" />
<style>
@media screen and (max-width: 1060px) {
.STHSWarning {display:block;}
table.basictablesorter thead th:nth-last-child(3){display:none;}
table.basictablesorter tbody td:nth-last-child(3){display:none;}
table.basictablesorter thead th:nth-last-child(4){display:none;}
table.basictablesorter tbody td:nth-last-child(4){display:none;}
table.basictablesorter thead th:nth-last-child(5){display:none;}
table.basictablesorter tbody td:nth-last-child(5){display:none;}
}@media screen and (max-width: 890px) {
table.basictablesorter thead th:nth-last-child(6){display:none;}
table.basictablesorter tbody td:nth-last-child(6){display:none;}
table.basictablesorter thead th:nth-last-child(7){display:none;}
table.basictablesorter tbody td:nth-last-child(7){display:none;}
}
table.basictablesorter tbody td.staticTD {font-size:9pt;border-right:hidden; border-left:hidden;}
</style>
<?php If (file_exists("STHSMain-CSSOverwrite.css") == True){echo "<link href=\"STHSMain-CSSOverwrite.css\" rel=\"stylesheet\" type=\"text/css\" />";}?>
<style>.tabsmenu{display:none;}</style> <!-- Do Not Show Top Menu STHS Option Apply -->
<?php $LeagueName = (string)"";
$DatabaseFile = (string)"ASHL11-STHS.db";
$LangOverwrite = (boolean)FALSE;
$CareerStatDatabaseFile = (string)"ASHL11-STHSCareerStat.db";
$lang = (string)"en"; /* The $lang option must be either "en" or "fr" */
if(isset($_GET['Lang'])){$lang  = filter_var($_GET['Lang'], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW || FILTER_FLAG_STRIP_HIGH);$LangOverwrite=TRUE;}  /* Allow Users Language Overwrite */
If ($lang == "fr"){include 'LanguageFR.php';}else{include 'LanguageEN.php';}
$db = new SQLite3($DatabaseFile);
$Active = 1; /* Show Webpage Top Menu */
include "Menu.php";?>
<script>$(function(){$("table").basictablesorter({ widgets: ['staticRow'] })});</script>
<div class="tabsmain standard"><ul class="tabmain-links">
<li class="activemain"><a href="#tabmain2">Conference</a></li>
<li><a href="#tabmain3">Division</a></li>
<li><a href="#tabmain4">Overall</a></li>
</ul><div class="tabmain-content">
<div class="tabmain active" id="tabmain2">
<h2 class="STHSStanding_H2Header">Eastern Conference</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="ASHL11-PRE-ProTeamRoster.php#PittsburghPenguins">Pittsburgh Penguins</a></td><td>4</td><td>4</td><td>0</td><td>0</td><td><b>8</b></td><td>4</td><td>12</td><td>4</td><td>8</td><td>1,000</td><td>2-0-0</td><td>2-0-0</td><td>4-0-0</td><td>2-0-0</td><td>2-0-0</td><td>W4</td><td></td></tr>
<tr><td>2</td><td><a href="ASHL11-PRE-ProTeamRoster.php#BuffaloSabres">Buffalo Sabres</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>13</td><td>11</td><td>2</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>L1</td><td></td></tr>
<tr><td>3</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ColumbusBlueJackets">Columbus Blue Jackets</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>19</td><td>10</td><td>9</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>4</td><td><a href="ASHL11-PRE-ProTeamRoster.php#CarolinaHurricanes">Carolina Hurricanes</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>2</td><td>13</td><td>11</td><td>2</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>W2</td><td></td></tr>
<tr><td>5</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewYorkRangers">New York Rangers</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>14</td><td>10</td><td>4</td><td>0,625</td><td>2-0-0</td><td>0-1-1</td><td>2-1-1</td><td>2-0-0</td><td>0-1-1</td><td>SOL1</td><td></td></tr>
<tr><td>6</td><td><a href="ASHL11-PRE-ProTeamRoster.php#OttawaSenators">Ottawa Senators</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,625</td><td>1-1-0</td><td>1-0-1</td><td>2-1-1</td><td>1-1-0</td><td>1-0-1</td><td>SOL1</td><td></td></tr>
<tr><td>7</td><td><a href="ASHL11-PRE-ProTeamRoster.php#FloridaPanthers">Florida Panthers</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,625</td><td>2-0-0</td><td>0-1-1</td><td>2-1-1</td><td>2-0-0</td><td>0-1-1</td><td>L1</td><td></td></tr>
<tr><td>8</td><td><a href="ASHL11-PRE-ProTeamRoster.php#WashingtonCapitals">Washington Capitals</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>11</td><td>12</td><td>-1</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>W1</td><td></td></tr>
<tr class="static"><td colspan="19"><hr /></td></tr>
<tr><td>9</td><td><a href="ASHL11-PRE-ProTeamRoster.php#PhiladelphiaFlyers">Philadelphia Flyers</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>7</td><td>9</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>10</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewJerseyDevils">New Jersey Devils</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>8</td><td>10</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>11</td><td><a href="ASHL11-PRE-ProTeamRoster.php#QuebecNordiques">Quebec Nordiques</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>9</td><td>14</td><td>-5</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>W2</td><td></td></tr>
<tr><td>12</td><td><a href="ASHL11-PRE-ProTeamRoster.php#MontrealCanadiens">Montreal Canadiens</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>15</td><td>11</td><td>4</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>L2</td><td></td></tr>
<tr><td>13</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewYorkIslanders">New York Islanders</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>1</td><td>14</td><td>15</td><td>-1</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>14</td><td><a href="ASHL11-PRE-ProTeamRoster.php#TorontoMapleLeafs">Toronto Maple Leafs</a></td><td>4</td><td>1</td><td>2</td><td>1</td><td><b>3</b></td><td>1</td><td>11</td><td>13</td><td>-2</td><td>0,375</td><td>1-1-0</td><td>0-1-1</td><td>1-2-1</td><td>1-1-0</td><td>0-1-1</td><td>L1</td><td>1</td></tr>
<tr><td>15</td><td><a href="ASHL11-PRE-ProTeamRoster.php#BostonBruins">Boston Bruins</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>14</td><td>-6</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>L1</td><td>2</td></tr>
<tr><td>16</td><td><a href="ASHL11-PRE-ProTeamRoster.php#TampaBayLightning">Tampa Bay Lightning</a></td><td>4</td><td>0</td><td>4</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>14</td><td>-8</td><td>0,000</td><td>0-2-0</td><td>0-2-0</td><td>0-4-0</td><td>0-2-0</td><td>0-2-0</td><td>L4</td><td>4</td></tr>
</tbody></table><br />
<h2 class="STHSStanding_H2Header">Western Conference</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ColoradoAvalanche">Colorado Avalanche</a></td><td>4</td><td>3</td><td>0</td><td>1</td><td><b>7</b></td><td>3</td><td>16</td><td>12</td><td>4</td><td>0,875</td><td>1-0-1</td><td>2-0-0</td><td>3-0-1</td><td>1-0-1</td><td>2-0-0</td><td>W3</td><td></td></tr>
<tr><td>2</td><td><a href="ASHL11-PRE-ProTeamRoster.php#VancouverCanucks">Vancouver Canucks</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>12</td><td>8</td><td>4</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>3</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NashvillePredators">Nashville Predators</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>14</td><td>8</td><td>6</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>4</td><td><a href="ASHL11-PRE-ProTeamRoster.php#LosAngelesKings">Los Angeles Kings</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>13</td><td>10</td><td>3</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>W3</td><td></td></tr>
<tr><td>5</td><td><a href="ASHL11-PRE-ProTeamRoster.php#VegasGoldenKnights">Vegas Golden Knights</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>10</td><td>11</td><td>-1</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>6</td><td><a href="ASHL11-PRE-ProTeamRoster.php#EdmontonOilers">Edmonton Oilers</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>18</td><td>11</td><td>7</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W3</td><td></td></tr>
<tr><td>7</td><td><a href="ASHL11-PRE-ProTeamRoster.php#St.LouisBlues">St. Louis Blues</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>9</td><td>9</td><td>0</td><td>0,625</td><td>1-0-1</td><td>1-1-0</td><td>2-1-1</td><td>1-0-1</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>8</td><td><a href="ASHL11-PRE-ProTeamRoster.php#DetroitRedWings">Detroit Red Wings</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>14</td><td>10</td><td>4</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>L1</td><td></td></tr>
<tr class="static"><td colspan="19"><hr /></td></tr>
<tr><td>9</td><td><a href="ASHL11-PRE-ProTeamRoster.php#AnaheimDucks">Anaheim Ducks</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>10</td><td><a href="ASHL11-PRE-ProTeamRoster.php#SeattleKraken">Seattle Kraken</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>16</td><td>15</td><td>1</td><td>0,500</td><td>0-2-0</td><td>2-0-0</td><td>2-2-0</td><td>0-2-0</td><td>2-0-0</td><td>W1</td><td></td></tr>
<tr><td>11</td><td><a href="ASHL11-PRE-ProTeamRoster.php#WinnipegJets">Winnipeg Jets</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>1</td><td>12</td><td>10</td><td>2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L2</td><td></td></tr>
<tr><td>12</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ChicagoBlackhawks">Chicago Blackhawks</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>12</td><td>14</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>13</td><td><a href="ASHL11-PRE-ProTeamRoster.php#SanJoseSharks">San Jose Sharks</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>11</td><td>-3</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>W1</td><td>2</td></tr>
<tr><td>14</td><td><a href="ASHL11-PRE-ProTeamRoster.php#DallasStars">Dallas Stars</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>5</td><td>8</td><td>-3</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>L1</td><td>2</td></tr>
<tr><td>15</td><td><a href="ASHL11-PRE-ProTeamRoster.php#MinnesotaWild">Minnesota Wild</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>16</td><td>-8</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>W1</td><td>2</td></tr>
<tr><td>16</td><td><a href="ASHL11-PRE-ProTeamRoster.php#CalgaryFlames">Calgary Flames</a></td><td>4</td><td>0</td><td>2</td><td>2</td><td><b>2</b></td><td>0</td><td>6</td><td>18</td><td>-12</td><td>0,250</td><td>0-0-2</td><td>0-2-0</td><td>0-2-2</td><td>0-0-2</td><td>0-2-0</td><td>OTL1</td><td>2</td></tr>
<tr><td>17</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ArizonaCoyotes">Arizona Coyotes</a></td><td>4</td><td>0</td><td>4</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>13</td><td>-7</td><td>0,000</td><td>0-2-0</td><td>0-2-0</td><td>0-4-0</td><td>0-2-0</td><td>0-2-0</td><td>L4</td><td>4</td></tr>
</tbody></table><br />
x - Clinched Playoff Berth<br />
y - Clinched Division Title<br />
z - Clinched Conference Title<br />
e - Eliminated<br />
*Seeding 1 division leaders<br />
</div><div class="tabmain" id="tabmain3">
<h2 class="STHSStanding_H2Header">Métropolitaine</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="ASHL11-PRE-ProTeamRoster.php#PittsburghPenguins">Pittsburgh Penguins</a></td><td>4</td><td>4</td><td>0</td><td>0</td><td><b>8</b></td><td>4</td><td>12</td><td>4</td><td>8</td><td>1,000</td><td>2-0-0</td><td>2-0-0</td><td>4-0-0</td><td>2-0-0</td><td>2-0-0</td><td>W4</td><td></td></tr>
<tr><td>2</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ColumbusBlueJackets">Columbus Blue Jackets</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>19</td><td>10</td><td>9</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>3</td><td><a href="ASHL11-PRE-ProTeamRoster.php#CarolinaHurricanes">Carolina Hurricanes</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>2</td><td>13</td><td>11</td><td>2</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>W2</td><td></td></tr>
<tr><td>4</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewYorkRangers">New York Rangers</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>14</td><td>10</td><td>4</td><td>0,625</td><td>2-0-0</td><td>0-1-1</td><td>2-1-1</td><td>2-0-0</td><td>0-1-1</td><td>SOL1</td><td></td></tr>
<tr><td>5</td><td><a href="ASHL11-PRE-ProTeamRoster.php#WashingtonCapitals">Washington Capitals</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>11</td><td>12</td><td>-1</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>W1</td><td></td></tr>
<tr><td>6</td><td><a href="ASHL11-PRE-ProTeamRoster.php#PhiladelphiaFlyers">Philadelphia Flyers</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>7</td><td>9</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>7</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewJerseyDevils">New Jersey Devils</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>8</td><td>10</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>8</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewYorkIslanders">New York Islanders</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>1</td><td>14</td><td>15</td><td>-1</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
</tbody></table>
<h2 class="STHSStanding_H2Header">Atlantique</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="ASHL11-PRE-ProTeamRoster.php#BuffaloSabres">Buffalo Sabres</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>13</td><td>11</td><td>2</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>L1</td><td></td></tr>
<tr><td>2</td><td><a href="ASHL11-PRE-ProTeamRoster.php#OttawaSenators">Ottawa Senators</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,625</td><td>1-1-0</td><td>1-0-1</td><td>2-1-1</td><td>1-1-0</td><td>1-0-1</td><td>SOL1</td><td></td></tr>
<tr><td>3</td><td><a href="ASHL11-PRE-ProTeamRoster.php#FloridaPanthers">Florida Panthers</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,625</td><td>2-0-0</td><td>0-1-1</td><td>2-1-1</td><td>2-0-0</td><td>0-1-1</td><td>L1</td><td></td></tr>
<tr><td>4</td><td><a href="ASHL11-PRE-ProTeamRoster.php#QuebecNordiques">Quebec Nordiques</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>9</td><td>14</td><td>-5</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>W2</td><td></td></tr>
<tr><td>5</td><td><a href="ASHL11-PRE-ProTeamRoster.php#MontrealCanadiens">Montreal Canadiens</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>15</td><td>11</td><td>4</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>L2</td><td></td></tr>
<tr><td>6</td><td><a href="ASHL11-PRE-ProTeamRoster.php#TorontoMapleLeafs">Toronto Maple Leafs</a></td><td>4</td><td>1</td><td>2</td><td>1</td><td><b>3</b></td><td>1</td><td>11</td><td>13</td><td>-2</td><td>0,375</td><td>1-1-0</td><td>0-1-1</td><td>1-2-1</td><td>1-1-0</td><td>0-1-1</td><td>L1</td><td>1</td></tr>
<tr><td>7</td><td><a href="ASHL11-PRE-ProTeamRoster.php#BostonBruins">Boston Bruins</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>14</td><td>-6</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>L1</td><td>2</td></tr>
<tr><td>8</td><td><a href="ASHL11-PRE-ProTeamRoster.php#TampaBayLightning">Tampa Bay Lightning</a></td><td>4</td><td>0</td><td>4</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>14</td><td>-8</td><td>0,000</td><td>0-2-0</td><td>0-2-0</td><td>0-4-0</td><td>0-2-0</td><td>0-2-0</td><td>L4</td><td>4</td></tr>
</tbody></table>
<h2 class="STHSStanding_H2Header">Centrale</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ColoradoAvalanche">Colorado Avalanche</a></td><td>4</td><td>3</td><td>0</td><td>1</td><td><b>7</b></td><td>3</td><td>16</td><td>12</td><td>4</td><td>0,875</td><td>1-0-1</td><td>2-0-0</td><td>3-0-1</td><td>1-0-1</td><td>2-0-0</td><td>W3</td><td></td></tr>
<tr><td>2</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NashvillePredators">Nashville Predators</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>14</td><td>8</td><td>6</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>3</td><td><a href="ASHL11-PRE-ProTeamRoster.php#St.LouisBlues">St. Louis Blues</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>9</td><td>9</td><td>0</td><td>0,625</td><td>1-0-1</td><td>1-1-0</td><td>2-1-1</td><td>1-0-1</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>4</td><td><a href="ASHL11-PRE-ProTeamRoster.php#DetroitRedWings">Detroit Red Wings</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>14</td><td>10</td><td>4</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>L1</td><td></td></tr>
<tr><td>5</td><td><a href="ASHL11-PRE-ProTeamRoster.php#WinnipegJets">Winnipeg Jets</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>1</td><td>12</td><td>10</td><td>2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L2</td><td></td></tr>
<tr><td>6</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ChicagoBlackhawks">Chicago Blackhawks</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>12</td><td>14</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>7</td><td><a href="ASHL11-PRE-ProTeamRoster.php#DallasStars">Dallas Stars</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>5</td><td>8</td><td>-3</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>L1</td><td>2</td></tr>
<tr><td>8</td><td><a href="ASHL11-PRE-ProTeamRoster.php#MinnesotaWild">Minnesota Wild</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>16</td><td>-8</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>W1</td><td>2</td></tr>
</tbody></table>
<h2 class="STHSStanding_H2Header">Pacifique</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="ASHL11-PRE-ProTeamRoster.php#VancouverCanucks">Vancouver Canucks</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>12</td><td>8</td><td>4</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>2</td><td><a href="ASHL11-PRE-ProTeamRoster.php#LosAngelesKings">Los Angeles Kings</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>13</td><td>10</td><td>3</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>W3</td><td></td></tr>
<tr><td>3</td><td><a href="ASHL11-PRE-ProTeamRoster.php#VegasGoldenKnights">Vegas Golden Knights</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>10</td><td>11</td><td>-1</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>4</td><td><a href="ASHL11-PRE-ProTeamRoster.php#EdmontonOilers">Edmonton Oilers</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>18</td><td>11</td><td>7</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W3</td><td></td></tr>
<tr><td>5</td><td><a href="ASHL11-PRE-ProTeamRoster.php#AnaheimDucks">Anaheim Ducks</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>6</td><td><a href="ASHL11-PRE-ProTeamRoster.php#SeattleKraken">Seattle Kraken</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>16</td><td>15</td><td>1</td><td>0,500</td><td>0-2-0</td><td>2-0-0</td><td>2-2-0</td><td>0-2-0</td><td>2-0-0</td><td>W1</td><td></td></tr>
<tr><td>7</td><td><a href="ASHL11-PRE-ProTeamRoster.php#SanJoseSharks">San Jose Sharks</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>11</td><td>-3</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>W1</td><td>2</td></tr>
<tr><td>8</td><td><a href="ASHL11-PRE-ProTeamRoster.php#CalgaryFlames">Calgary Flames</a></td><td>4</td><td>0</td><td>2</td><td>2</td><td><b>2</b></td><td>0</td><td>6</td><td>18</td><td>-12</td><td>0,250</td><td>0-0-2</td><td>0-2-0</td><td>0-2-2</td><td>0-0-2</td><td>0-2-0</td><td>OTL1</td><td>2</td></tr>
<tr><td>9</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ArizonaCoyotes">Arizona Coyotes</a></td><td>4</td><td>0</td><td>4</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>13</td><td>-7</td><td>0,000</td><td>0-2-0</td><td>0-2-0</td><td>0-4-0</td><td>0-2-0</td><td>0-2-0</td><td>L4</td><td>4</td></tr>
</tbody></table>
</div><div class="tabmain" id="tabmain4">
<h2 class="STHSStanding_H2Header">Overall</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="ASHL11-PRE-ProTeamRoster.php#PittsburghPenguins">Pittsburgh Penguins</a></td><td>4</td><td>4</td><td>0</td><td>0</td><td><b>8</b></td><td>4</td><td>12</td><td>4</td><td>8</td><td>1,000</td><td>2-0-0</td><td>2-0-0</td><td>4-0-0</td><td>2-0-0</td><td>2-0-0</td><td>W4</td><td></td></tr>
<tr><td>2</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ColoradoAvalanche">Colorado Avalanche</a></td><td>4</td><td>3</td><td>0</td><td>1</td><td><b>7</b></td><td>3</td><td>16</td><td>12</td><td>4</td><td>0,875</td><td>1-0-1</td><td>2-0-0</td><td>3-0-1</td><td>1-0-1</td><td>2-0-0</td><td>W3</td><td></td></tr>
<tr><td>3</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ColumbusBlueJackets">Columbus Blue Jackets</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>19</td><td>10</td><td>9</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>4</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NashvillePredators">Nashville Predators</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>14</td><td>8</td><td>6</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>5</td><td><a href="ASHL11-PRE-ProTeamRoster.php#VancouverCanucks">Vancouver Canucks</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>12</td><td>8</td><td>4</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>6</td><td><a href="ASHL11-PRE-ProTeamRoster.php#LosAngelesKings">Los Angeles Kings</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>13</td><td>10</td><td>3</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>W3</td><td></td></tr>
<tr><td>7</td><td><a href="ASHL11-PRE-ProTeamRoster.php#BuffaloSabres">Buffalo Sabres</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>13</td><td>11</td><td>2</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>L1</td><td></td></tr>
<tr><td>8</td><td><a href="ASHL11-PRE-ProTeamRoster.php#VegasGoldenKnights">Vegas Golden Knights</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>10</td><td>11</td><td>-1</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>9</td><td><a href="ASHL11-PRE-ProTeamRoster.php#EdmontonOilers">Edmonton Oilers</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>3</td><td>18</td><td>11</td><td>7</td><td>0,750</td><td>2-0-0</td><td>1-1-0</td><td>3-1-0</td><td>2-0-0</td><td>1-1-0</td><td>W3</td><td></td></tr>
<tr><td>10</td><td><a href="ASHL11-PRE-ProTeamRoster.php#CarolinaHurricanes">Carolina Hurricanes</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>6</b></td><td>2</td><td>13</td><td>11</td><td>2</td><td>0,750</td><td>1-1-0</td><td>2-0-0</td><td>3-1-0</td><td>1-1-0</td><td>2-0-0</td><td>W2</td><td></td></tr>
<tr><td>11</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewYorkRangers">New York Rangers</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>14</td><td>10</td><td>4</td><td>0,625</td><td>2-0-0</td><td>0-1-1</td><td>2-1-1</td><td>2-0-0</td><td>0-1-1</td><td>SOL1</td><td></td></tr>
<tr><td>12</td><td><a href="ASHL11-PRE-ProTeamRoster.php#OttawaSenators">Ottawa Senators</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,625</td><td>1-1-0</td><td>1-0-1</td><td>2-1-1</td><td>1-1-0</td><td>1-0-1</td><td>SOL1</td><td></td></tr>
<tr><td>13</td><td><a href="ASHL11-PRE-ProTeamRoster.php#FloridaPanthers">Florida Panthers</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,625</td><td>2-0-0</td><td>0-1-1</td><td>2-1-1</td><td>2-0-0</td><td>0-1-1</td><td>L1</td><td></td></tr>
<tr><td>14</td><td><a href="ASHL11-PRE-ProTeamRoster.php#St.LouisBlues">St. Louis Blues</a></td><td>4</td><td>2</td><td>1</td><td>1</td><td><b>5</b></td><td>2</td><td>9</td><td>9</td><td>0</td><td>0,625</td><td>1-0-1</td><td>1-1-0</td><td>2-1-1</td><td>1-0-1</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>15</td><td><a href="ASHL11-PRE-ProTeamRoster.php#DetroitRedWings">Detroit Red Wings</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>14</td><td>10</td><td>4</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>L1</td><td></td></tr>
<tr><td>16</td><td><a href="ASHL11-PRE-ProTeamRoster.php#AnaheimDucks">Anaheim Ducks</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>10</td><td>9</td><td>1</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>17</td><td><a href="ASHL11-PRE-ProTeamRoster.php#SeattleKraken">Seattle Kraken</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>16</td><td>15</td><td>1</td><td>0,500</td><td>0-2-0</td><td>2-0-0</td><td>2-2-0</td><td>0-2-0</td><td>2-0-0</td><td>W1</td><td></td></tr>
<tr><td>18</td><td><a href="ASHL11-PRE-ProTeamRoster.php#WashingtonCapitals">Washington Capitals</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>11</td><td>12</td><td>-1</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>W1</td><td></td></tr>
<tr><td>19</td><td><a href="ASHL11-PRE-ProTeamRoster.php#PhiladelphiaFlyers">Philadelphia Flyers</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>7</td><td>9</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>20</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewJerseyDevils">New Jersey Devils</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>8</td><td>10</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L1</td><td></td></tr>
<tr><td>21</td><td><a href="ASHL11-PRE-ProTeamRoster.php#QuebecNordiques">Quebec Nordiques</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>9</td><td>14</td><td>-5</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>W2</td><td></td></tr>
<tr><td>22</td><td><a href="ASHL11-PRE-ProTeamRoster.php#MontrealCanadiens">Montreal Canadiens</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>15</td><td>11</td><td>4</td><td>0,500</td><td>2-0-0</td><td>0-2-0</td><td>2-2-0</td><td>2-0-0</td><td>0-2-0</td><td>L2</td><td></td></tr>
<tr><td>23</td><td><a href="ASHL11-PRE-ProTeamRoster.php#WinnipegJets">Winnipeg Jets</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>1</td><td>12</td><td>10</td><td>2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>L2</td><td></td></tr>
<tr><td>24</td><td><a href="ASHL11-PRE-ProTeamRoster.php#NewYorkIslanders">New York Islanders</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>1</td><td>14</td><td>15</td><td>-1</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>25</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ChicagoBlackhawks">Chicago Blackhawks</a></td><td>4</td><td>2</td><td>2</td><td>0</td><td><b>4</b></td><td>2</td><td>12</td><td>14</td><td>-2</td><td>0,500</td><td>1-1-0</td><td>1-1-0</td><td>2-2-0</td><td>1-1-0</td><td>1-1-0</td><td>W1</td><td></td></tr>
<tr><td>26</td><td><a href="ASHL11-PRE-ProTeamRoster.php#TorontoMapleLeafs">Toronto Maple Leafs</a></td><td>4</td><td>1</td><td>2</td><td>1</td><td><b>3</b></td><td>1</td><td>11</td><td>13</td><td>-2</td><td>0,375</td><td>1-1-0</td><td>0-1-1</td><td>1-2-1</td><td>1-1-0</td><td>0-1-1</td><td>L1</td><td>1</td></tr>
<tr><td>27</td><td><a href="ASHL11-PRE-ProTeamRoster.php#SanJoseSharks">San Jose Sharks</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>11</td><td>-3</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>W1</td><td>2</td></tr>
<tr><td>28</td><td><a href="ASHL11-PRE-ProTeamRoster.php#DallasStars">Dallas Stars</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>5</td><td>8</td><td>-3</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>L1</td><td>2</td></tr>
<tr><td>29</td><td><a href="ASHL11-PRE-ProTeamRoster.php#BostonBruins">Boston Bruins</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>14</td><td>-6</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>L1</td><td>2</td></tr>
<tr><td>30</td><td><a href="ASHL11-PRE-ProTeamRoster.php#MinnesotaWild">Minnesota Wild</a></td><td>4</td><td>1</td><td>3</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>16</td><td>-8</td><td>0,250</td><td>1-1-0</td><td>0-2-0</td><td>1-3-0</td><td>1-1-0</td><td>0-2-0</td><td>W1</td><td>2</td></tr>
<tr><td>31</td><td><a href="ASHL11-PRE-ProTeamRoster.php#CalgaryFlames">Calgary Flames</a></td><td>4</td><td>0</td><td>2</td><td>2</td><td><b>2</b></td><td>0</td><td>6</td><td>18</td><td>-12</td><td>0,250</td><td>0-0-2</td><td>0-2-0</td><td>0-2-2</td><td>0-0-2</td><td>0-2-0</td><td>OTL1</td><td>2</td></tr>
<tr><td>32</td><td><a href="ASHL11-PRE-ProTeamRoster.php#ArizonaCoyotes">Arizona Coyotes</a></td><td>4</td><td>0</td><td>4</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>13</td><td>-7</td><td>0,000</td><td>0-2-0</td><td>0-2-0</td><td>0-4-0</td><td>0-2-0</td><td>0-2-0</td><td>L4</td><td>4</td></tr>
<tr><td>33</td><td><a href="ASHL11-PRE-ProTeamRoster.php#TampaBayLightning">Tampa Bay Lightning</a></td><td>4</td><td>0</td><td>4</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>14</td><td>-8</td><td>0,000</td><td>0-2-0</td><td>0-2-0</td><td>0-4-0</td><td>0-2-0</td><td>0-2-0</td><td>L4</td><td>4</td></tr>
</tbody></table></div></div></div>
<h2 class="STHSStanding_PointSystem">Point System</h2>
<b>Win :</b> 2 -- <b>Loss :</b> 0 -- <b>OT Win :</b> 2 -- <b>OT Loss :</b> 1 -- <b>SO Win :</b> 2 -- <b>SO Loss :</b> 1<br /><br />P.S. The simulator only uses points to give the title. If two team have the same amount of point, none of them will be award the title until your simulate the last game/day of your season.
<?php include "Footer.php";?>
